"""Type stubs for cheat-ccv3-pp-py

Provides type hints and autocomplete support for IDEs.
"""

from typing import Optional, Union

class Beatmap:
    """Beatmap parsed from .osu file"""

    def __init__(
        self,
        *,
        path: Optional[str] = None,
        content: Optional[str] = None,
        bytes: Optional[bytes] = None,
    ) -> None: ...
    
    @property
    def mode(self) -> str: ...
    @property
    def ar(self) -> float: ...
    @property
    def cs(self) -> float: ...
    @property
    def hp(self) -> float: ...
    @property
    def od(self) -> float: ...
    @property
    def bpm(self) -> float: ...
    @property
    def n_circles(self) -> int: ...
    @property
    def n_sliders(self) -> int: ...
    @property
    def n_spinners(self) -> int: ...
    
    def stars(self) -> Difficulty: ...
    def pp(self) -> Performance: ...
    def max_pp(self, mods: int) -> PerformanceAttributes: ...
    def max_stars(self, mods: int) -> DifficultyAttributes: ...

class Difficulty:
    """Calculate star rating and difficulty metrics"""

    def __init__(
        self,
        beatmap: Beatmap,
        *,
        mods: int = 0,
        passed_objects: Optional[int] = None,
        clock_rate: Optional[float] = None,
        is_convert: Optional[bool] = None,
    ) -> None: ...
    
    def mods(self, mods: int) -> Difficulty: ...
    def passed_objects(self, count: int) -> Difficulty: ...
    def clock_rate(self, rate: float) -> Difficulty: ...
    def is_convert(self, is_convert: bool) -> Difficulty: ...
    def calculate(self) -> DifficultyAttributes: ...

class DifficultyAttributes:
    """Result of difficulty calculation"""

    @property
    def stars(self) -> float: ...
    @property
    def max_combo(self) -> int: ...
    
    # osu! specific
    @property
    def aim(self) -> Optional[float]: ...
    @property
    def speed(self) -> Optional[float]: ...
    @property
    def flashlight(self) -> Optional[float]: ...
    @property
    def slider_factor(self) -> Optional[float]: ...
    @property
    def speed_note_count(self) -> Optional[float]: ...
    @property
    def n_circles(self) -> Optional[int]: ...
    @property
    def n_sliders(self) -> Optional[int]: ...
    @property
    def n_spinners(self) -> Optional[int]: ...
    @property
    def local_sr_per_minute(self) -> Optional[list[float]]: ...
    @property
    def local_sr_per_15s(self) -> Optional[list[float]]: ...
    
    # Universal
    @property
    def ar(self) -> Optional[float]: ...
    @property
    def od(self) -> Optional[float]: ...
    @property
    def hp(self) -> Optional[float]: ...
    
    # taiko
    @property
    def stamina(self) -> Optional[float]: ...
    @property
    def rhythm(self) -> Optional[float]: ...
    @property
    def color(self) -> Optional[float]: ...
    @property
    def peak(self) -> Optional[float]: ...
    
    # catch
    @property
    def n_fruits(self) -> Optional[int]: ...
    @property
    def n_droplets(self) -> Optional[int]: ...
    @property
    def n_tiny_droplets(self) -> Optional[int]: ...
    
    # Universal
    @property
    def hit_window(self) -> Optional[float]: ...

class Performance:
    """Calculate performance points and metrics"""

    def __init__(
        self,
        beatmap: Beatmap,
        *,
        mods: int = 0,
        combo: Optional[int] = None,
        accuracy: Optional[float] = None,
        misses: Optional[int] = None,
        n300: Optional[int] = None,
        n100: Optional[int] = None,
        n50: Optional[int] = None,
        n_katu: Optional[int] = None,
        n_geki: Optional[int] = None,
        passed_objects: Optional[int] = None,
        clock_rate: Optional[float] = None,
        is_convert: Optional[bool] = None,
    ) -> None: ...
    
    def mods(self, mods: int) -> Performance: ...
    def combo(self, combo: int) -> Performance: ...
    def accuracy(self, acc: float) -> Performance: ...
    def misses(self, count: int) -> Performance: ...
    def n_misses(self, count: int) -> Performance: ...
    def n300(self, count: int) -> Performance: ...
    def n100(self, count: int) -> Performance: ...
    def n50(self, count: int) -> Performance: ...
    def n_katu(self, count: int) -> Performance: ...
    def n_geki(self, count: int) -> Performance: ...
    def passed_objects(self, count: int) -> Performance: ...
    def clock_rate(self, rate: float) -> Performance: ...
    def is_convert(self, is_convert: bool) -> Performance: ...
    def calculate(self) -> PerformanceAttributes: ...

class PerformanceAttributes:
    """Result of performance calculation"""

    @property
    def pp(self) -> float: ...
    @property
    def stars(self) -> float: ...
    @property
    def max_combo(self) -> int: ...
    
    # osu! & taiko
    @property
    def pp_acc(self) -> Optional[float]: ...
    
    # osu!
    @property
    def pp_aim(self) -> Optional[float]: ...
    @property
    def pp_speed(self) -> Optional[float]: ...
    @property
    def pp_flashlight(self) -> Optional[float]: ...
    
    # taiko & mania
    @property
    def pp_difficulty(self) -> Optional[float]: ...
    
    # osu! & taiko
    @property
    def effective_miss_count(self) -> Optional[float]: ...
    
    @property
    def difficulty(self) -> DifficultyAttributes: ...

class ScoreState:
    """Score state with hit result breakdown"""

    def __init__(
        self, combo: int, n_300: int, n_100: int, n_50: int, misses: int
    ) -> None: ...
    
    @property
    def combo(self) -> int: ...
    @property
    def n_300(self) -> int: ...
    @property
    def n_100(self) -> int: ...
    @property
    def n_50(self) -> int: ...
    @property
    def misses(self) -> int: ...

class Strains:
    """Strain values from difficulty calculation"""

    def __init__(
        self,
        aim: Optional[float],
        speed: Optional[float],
        flashlight: Optional[float],
    ) -> None: ...
    
    @property
    def aim(self) -> Optional[float]: ...
    @property
    def speed(self) -> Optional[float]: ...
    @property
    def flashlight(self) -> Optional[float]: ...

class GameMods:
    """Game modifiers bitmask"""

    def __init__(self, bits: int) -> None: ...
    
    @property
    def bits(self) -> int: ...
    
    def contains(self, mod_bits: int) -> bool: ...
    def add(self, mod_bits: int) -> None: ...
    def remove(self, mod_bits: int) -> None: ...

class ParseError(ValueError):
    """Raised when beatmap parsing fails"""

class ArgsError(TypeError):
    """Raised when invalid arguments are passed"""

# Mod constants
NO_MOD: int
NF: int
EZ: int
TD: int
HD: int
HR: int
SD: int
DT: int
RL: int
HT: int
NC: int
FL: int
SO: int
AU: int
AP: int
CN: int
